package de.gtacity.client.render;

import de.gtacity.GtaCity;
import de.gtacity.entity.CarVariant;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Box model of a car. Texture layout (256x160) is generated by tools/gen_cars.py, keep the sizes in sync:
 * body at (0,0), cabin at (0,80), wheel at (200,0), bumper at (140,80), light bar at (140,90).
 */
public class CarModel extends EntityModel<CarRenderer.State> {
    private final ModelPart wheelFrontLeft;
    private final ModelPart wheelFrontRight;
    private final ModelPart wheelBackLeft;
    private final ModelPart wheelBackRight;
    private final ModelPart lightBar;
    private final ModelPart doorDriver;
    private final ModelPart doorPassenger;

    public CarModel(ModelPart root) {
        super(root);
        wheelFrontLeft = root.getChild("wheel_fl");
        wheelFrontRight = root.getChild("wheel_fr");
        wheelBackLeft = root.getChild("wheel_bl");
        wheelBackRight = root.getChild("wheel_br");
        lightBar = root.getChild("light_bar");
        doorDriver = root.getChild("door_driver");
        doorPassenger = root.getChild("door_passenger");
    }

    public static ModelLayerLocation layer(CarVariant.Shape shape) {
        return new ModelLayerLocation(GtaCity.id("car_" + shape.name().toLowerCase()), "main");
    }

    /** {body w, h, d, cabin w, h, d, cabin z offset} in pixels. */
    private static int[] dims(CarVariant.Shape shape) {
        return switch (shape) {
            case SEDAN -> new int[]{28, 10, 64, 24, 9, 32, 4};
            case SPORTS -> new int[]{28, 8, 62, 24, 7, 26, 6};
            case SUV -> new int[]{30, 13, 66, 28, 11, 40, 6};
            case SUPER -> new int[]{30, 5, 54, 20, 4, 20, 4};
        };
    }

    public static LayerDefinition create(CarVariant.Shape shape) {
        if (shape == CarVariant.Shape.SUPER) {
            return createSuper();
        }
        int[] d = dims(shape);
        int w = d[0], h = d[1], len = d[2], cw = d[3], ch = d[4], cd = d[5], off = d[6];
        float bottom = 20.0F;
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0)
                .addBox(-w / 2.0F, bottom - h, -len / 2.0F, w, h, len), PartPose.ZERO);
        root.addOrReplaceChild("cabin", CubeListBuilder.create().texOffs(0, 80)
                .addBox(-cw / 2.0F, bottom - h - ch, -cd / 2.0F + off, cw, ch, cd), PartPose.ZERO);
        root.addOrReplaceChild("bumper_front", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-w / 2.0F, bottom - 4, -len / 2.0F - 2, w, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("bumper_back", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-w / 2.0F, bottom - 4, len / 2.0F, w, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("light_bar", CubeListBuilder.create().texOffs(140, 90)
                .addBox(-8.0F, bottom - h - ch - 2, -2.0F + off, 16, 2, 4), PartPose.ZERO);
        // Rear wing on stands - supercars only (empty part for the others, so every layer has the same parts).
        CubeListBuilder wing = CubeListBuilder.create();
        if (shape == CarVariant.Shape.SUPER) {
            float wingZ = len / 2.0F - 7.0F;
            wing.texOffs(140, 100).addBox(-13.0F, bottom - h - 6, wingZ, 26, 2, 6)
                    .texOffs(140, 112).addBox(-9.0F, bottom - h - 4, wingZ + 2, 2, 4, 2)
                    .texOffs(140, 112).addBox(7.0F, bottom - h - 4, wingZ + 2, 2, 4, 2);
        }
        root.addOrReplaceChild("spoiler", wing, PartPose.ZERO);
        CubeListBuilder wheel = CubeListBuilder.create().texOffs(200, 0).addBox(-2.0F, -5.0F, -5.0F, 4, 10, 10);
        float wx = w / 2.0F - 1.0F;
        float wz = len / 2.0F - 12.0F;
        root.addOrReplaceChild("wheel_fl", wheel, PartPose.offset(wx, 19.0F, -wz));
        root.addOrReplaceChild("wheel_fr", wheel, PartPose.offset(-wx, 19.0F, -wz));
        root.addOrReplaceChild("wheel_bl", wheel, PartPose.offset(wx, 19.0F, wz));
        root.addOrReplaceChild("wheel_br", wheel, PartPose.offset(-wx, 19.0F, wz));
        // Front doors, hinged at the front edge: a body coloured panel with the window above it.
        int doorLen = (int) Math.min(18.0F, cd * 0.6F);
        float hingeZ = -cd / 2.0F + off;
        float inset = (w - cw) / 2.0F;
        for (int side : new int[]{1, -1}) {
            float x0 = side > 0 ? 0.0F : -0.6F;
            CubeListBuilder door = CubeListBuilder.create()
                    // UV offsets chosen so the door's side faces show the body's and the cabin's side texture.
                    .texOffs(20, len - doorLen).addBox(x0, bottom - h, 0.0F, 0.6F, h - 3, doorLen)
                    .texOffs(0, 80 + cd - doorLen).addBox(x0 - side * inset, bottom - h - ch, 0.0F, 0.6F, ch,
                            doorLen);
            root.addOrReplaceChild(side > 0 ? "door_driver" : "door_passenger", door,
                    PartPose.offset(side * (w / 2.0F + 0.05F), 0.0F, hingeZ));
        }
        return LayerDefinition.create(mesh, 256, 160);
    }

    /**
     * The supercar: a low wedge. Flat nose, main body only five pixels high, a glass canopy set far back with a
     * raked windscreen in front of it, louvred engine cover, side intakes, mirrors, smaller wheels and a big wing on
     * tall stands. Texture layout (gen_cars.py): body (0,0) 30x5x54, cabin (0,80) 20x4x20, nose (0,110) 28x3x14,
     * engine cover (0,130) 18x2x12, windscreen (88,80) 18x2x6, intake (150,120) 1x3x8, mirror (170,120) 2x1x1,
     * wheel (200,24) 4x9x9, wing (140,100) 28x1x6, stand (140,112) 2x6x2.
     */
    private static LayerDefinition createSuper() {
        float bottom = 21.0F;
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        float top = bottom - 5;
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0)
                .addBox(-15.0F, top, -20.0F, 30, 5, 54), PartPose.ZERO);
        root.addOrReplaceChild("nose", CubeListBuilder.create().texOffs(0, 110)
                .addBox(-14.0F, bottom - 3, -34.0F, 28, 3, 14), PartPose.ZERO);
        root.addOrReplaceChild("cabin", CubeListBuilder.create().texOffs(0, 80)
                .addBox(-10.0F, top - 4, -6.0F, 20, 4, 20), PartPose.ZERO);
        root.addOrReplaceChild("windscreen", CubeListBuilder.create().texOffs(88, 80)
                .addBox(-9.0F, top - 2, -12.0F, 18, 2, 6), PartPose.ZERO);
        root.addOrReplaceChild("engine_cover", CubeListBuilder.create().texOffs(0, 130)
                .addBox(-9.0F, top - 2, 14.0F, 18, 2, 12), PartPose.ZERO);
        root.addOrReplaceChild("intakes", CubeListBuilder.create()
                .texOffs(150, 120).addBox(15.0F, top + 1, 6.0F, 1, 3, 8)
                .texOffs(150, 120).addBox(-16.0F, top + 1, 6.0F, 1, 3, 8), PartPose.ZERO);
        root.addOrReplaceChild("mirrors", CubeListBuilder.create()
                .texOffs(170, 120).addBox(10.0F, top - 3, -5.0F, 2, 1, 1)
                .texOffs(170, 120).addBox(-12.0F, top - 3, -5.0F, 2, 1, 1), PartPose.ZERO);
        root.addOrReplaceChild("bumper_front", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-15.0F, bottom - 2, -36.0F, 30, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("bumper_back", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-15.0F, bottom - 3, 34.0F, 30, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("light_bar", CubeListBuilder.create().texOffs(140, 90)
                .addBox(-8.0F, top - 6, -2.0F, 16, 2, 4), PartPose.ZERO);
        root.addOrReplaceChild("spoiler", CubeListBuilder.create()
                .texOffs(140, 100).addBox(-14.0F, top - 7, 27.0F, 28, 1, 6)
                .texOffs(140, 112).addBox(-9.0F, top - 6, 29.0F, 2, 6, 2)
                .texOffs(140, 112).addBox(7.0F, top - 6, 29.0F, 2, 6, 2), PartPose.ZERO);
        CubeListBuilder wheel = CubeListBuilder.create().texOffs(200, 24).addBox(-2.0F, -4.5F, -4.5F, 4, 9, 9);
        root.addOrReplaceChild("wheel_fl", wheel, PartPose.offset(14.0F, 19.5F, -24.0F));
        root.addOrReplaceChild("wheel_fr", wheel, PartPose.offset(-14.0F, 19.5F, -24.0F));
        root.addOrReplaceChild("wheel_bl", wheel, PartPose.offset(14.0F, 19.5F, 22.0F));
        root.addOrReplaceChild("wheel_br", wheel, PartPose.offset(-14.0F, 19.5F, 22.0F));
        // Scissor doors: hinged at the front, they swing up.
        for (int side : new int[]{1, -1}) {
            float x0 = side > 0 ? 0.0F : -0.6F;
            CubeListBuilder door = CubeListBuilder.create()
                    .texOffs(20, 54 - 16).addBox(x0, 0.0F, 0.0F, 0.6F, 5, 16)
                    .texOffs(0, 80 + 20 - 16).addBox(x0 - side * 5.0F, -4.0F, 0.0F, 0.6F, 4, 16);
            root.addOrReplaceChild(side > 0 ? "door_driver" : "door_passenger", door,
                    PartPose.offset(side * 15.05F, top, -6.0F));
        }
        return LayerDefinition.create(mesh, 256, 160);
    }

    @Override
    public void setupAnim(CarRenderer.State state) {
        super.setupAnim(state);
        float roll = state.wheelRot * Mth.DEG_TO_RAD;
        wheelFrontLeft.xRot = roll;
        wheelFrontRight.xRot = roll;
        wheelBackLeft.xRot = roll;
        wheelBackRight.xRot = roll;
        float steer = -state.steer * 0.45F;
        wheelFrontLeft.yRot = steer;
        wheelFrontRight.yRot = steer;
        lightBar.visible = state.variant.hasLightBar() && (!state.siren || state.flash);
        if (state.variant.shape == CarVariant.Shape.SUPER) {
            // Scissor doors swing up.
            doorDriver.xRot = state.doorDriver * 1.1F;
            doorPassenger.xRot = state.doorPassenger * 1.1F;
        } else {
            doorDriver.yRot = state.doorDriver * 1.15F;
            doorPassenger.yRot = -state.doorPassenger * 1.15F;
        }
    }
}
