package de.gtacity.client.render;

import de.gtacity.GtaCity;
import de.gtacity.entity.CarVariant;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Box model of a car. Texture layout (256x160) is generated by tools/gen_cars.py, keep the sizes in sync:
 * body at (0,0), cabin at (0,80), wheel at (200,0), bumper at (140,80), light bar at (140,90).
 */
public class CarModel extends EntityModel<CarRenderer.State> {
    private final ModelPart wheelFrontLeft;
    private final ModelPart wheelFrontRight;
    private final ModelPart wheelBackLeft;
    private final ModelPart wheelBackRight;
    private final ModelPart lightBar;

    public CarModel(ModelPart root) {
        super(root);
        wheelFrontLeft = root.getChild("wheel_fl");
        wheelFrontRight = root.getChild("wheel_fr");
        wheelBackLeft = root.getChild("wheel_bl");
        wheelBackRight = root.getChild("wheel_br");
        lightBar = root.getChild("light_bar");
    }

    public static ModelLayerLocation layer(CarVariant.Shape shape) {
        return new ModelLayerLocation(GtaCity.id("car_" + shape.name().toLowerCase()), "main");
    }

    /** {body w, h, d, cabin w, h, d, cabin z offset} in pixels. */
    private static int[] dims(CarVariant.Shape shape) {
        return switch (shape) {
            case SEDAN -> new int[]{28, 10, 64, 24, 9, 32, 4};
            case SPORTS -> new int[]{28, 8, 62, 24, 7, 26, 6};
            case SUV -> new int[]{30, 13, 66, 28, 11, 40, 6};
            case SUPER -> new int[]{28, 7, 66, 22, 6, 24, 7};
        };
    }

    public static LayerDefinition create(CarVariant.Shape shape) {
        int[] d = dims(shape);
        int w = d[0], h = d[1], len = d[2], cw = d[3], ch = d[4], cd = d[5], off = d[6];
        float bottom = 20.0F;
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0)
                .addBox(-w / 2.0F, bottom - h, -len / 2.0F, w, h, len), PartPose.ZERO);
        root.addOrReplaceChild("cabin", CubeListBuilder.create().texOffs(0, 80)
                .addBox(-cw / 2.0F, bottom - h - ch, -cd / 2.0F + off, cw, ch, cd), PartPose.ZERO);
        root.addOrReplaceChild("bumper_front", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-w / 2.0F, bottom - 4, -len / 2.0F - 2, w, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("bumper_back", CubeListBuilder.create().texOffs(140, 80)
                .addBox(-w / 2.0F, bottom - 4, len / 2.0F, w, 3, 2), PartPose.ZERO);
        root.addOrReplaceChild("light_bar", CubeListBuilder.create().texOffs(140, 90)
                .addBox(-8.0F, bottom - h - ch - 2, -2.0F + off, 16, 2, 4), PartPose.ZERO);
        // Rear wing on stands - supercars only (empty part for the others, so every layer has the same parts).
        CubeListBuilder wing = CubeListBuilder.create();
        if (shape == CarVariant.Shape.SUPER) {
            float wingZ = len / 2.0F - 7.0F;
            wing.texOffs(140, 100).addBox(-13.0F, bottom - h - 6, wingZ, 26, 2, 6)
                    .texOffs(140, 112).addBox(-9.0F, bottom - h - 4, wingZ + 2, 2, 4, 2)
                    .texOffs(140, 112).addBox(7.0F, bottom - h - 4, wingZ + 2, 2, 4, 2);
        }
        root.addOrReplaceChild("spoiler", wing, PartPose.ZERO);
        CubeListBuilder wheel = CubeListBuilder.create().texOffs(200, 0).addBox(-2.0F, -5.0F, -5.0F, 4, 10, 10);
        float wx = w / 2.0F - 1.0F;
        float wz = len / 2.0F - 12.0F;
        root.addOrReplaceChild("wheel_fl", wheel, PartPose.offset(wx, 19.0F, -wz));
        root.addOrReplaceChild("wheel_fr", wheel, PartPose.offset(-wx, 19.0F, -wz));
        root.addOrReplaceChild("wheel_bl", wheel, PartPose.offset(wx, 19.0F, wz));
        root.addOrReplaceChild("wheel_br", wheel, PartPose.offset(-wx, 19.0F, wz));
        return LayerDefinition.create(mesh, 256, 160);
    }

    @Override
    public void setupAnim(CarRenderer.State state) {
        super.setupAnim(state);
        float roll = state.wheelRot * Mth.DEG_TO_RAD;
        wheelFrontLeft.xRot = roll;
        wheelFrontRight.xRot = roll;
        wheelBackLeft.xRot = roll;
        wheelBackRight.xRot = roll;
        float steer = -state.steer * 0.45F;
        wheelFrontLeft.yRot = steer;
        wheelFrontRight.yRot = steer;
        lightBar.visible = state.variant.hasLightBar() && (!state.siren || state.flash);
    }
}
