// Nur zum Uebersetzen - zur Laufzeit liefert Paper die echten Klassen.
package org.bukkit;
public abstract class Sound {
    public static Sound ENTITY_ITEM_PICKUP, ENTITY_PLAYER_ATTACK_SWEEP, ENTITY_PLAYER_ATTACK_STRONG, ENTITY_PLAYER_LEVELUP,
        ENTITY_EXPERIENCE_ORB_PICKUP, BLOCK_WOODEN_DOOR_OPEN, BLOCK_WOODEN_DOOR_CLOSE, ENTITY_GENERIC_EAT,
        BLOCK_FURNACE_FIRE_CRACKLE, BLOCK_CHEST_OPEN, BLOCK_CHEST_CLOSE, ENTITY_ENDERMAN_TELEPORT,
        BLOCK_NOTE_BLOCK_PLING, BLOCK_ANVIL_USE, ENTITY_VILLAGER_YES, ENTITY_PLAYER_BURP;
}
