package de.gtacity.registry;

import de.gtacity.GtaCity;
import de.gtacity.item.GunType;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.sounds.SoundSource;
import net.minecraft.sounds.SoundEvent;

/** The mod's own sounds (assets/gtacity/sounds, generated by tools/gen_sounds.py). */
public final class ModSounds {
    private ModSounds() {
    }

    public static final SoundEvent GUN_PISTOL = register("gun_pistol");
    public static final SoundEvent GUN_SMG = register("gun_smg");
    public static final SoundEvent GUN_RIFLE = register("gun_rifle");
    public static final SoundEvent GUN_SHOTGUN = register("gun_shotgun");
    public static final SoundEvent GUN_SNIPER = register("gun_sniper");
    public static final SoundEvent GUN_MINIGUN = register("gun_minigun");
    public static final SoundEvent RPG_LAUNCH = register("rpg_launch");
    public static final SoundEvent EXPLOSION = register("explosion");
    public static final SoundEvent RELOAD = register("reload");
    public static final SoundEvent DRY_FIRE = register("dry_fire");
    public static final SoundEvent HORN = register("horn");
    public static final SoundEvent ENGINE = register("engine");
    public static final SoundEvent ENGINE_SUPER = register("engine_super");
    public static final SoundEvent SIREN = register("siren");
    public static final SoundEvent HELI_ROTOR = register("heli_rotor");
    public static final SoundEvent SKID = register("skid");
    public static final SoundEvent CASH = register("cash");

    private static SoundEvent register(String name) {
        return Registry.register(BuiltInRegistries.SOUND_EVENT, GtaCity.id(name),
                SoundEvent.createVariableRangeEvent(GtaCity.id(name)));
    }

    public static SoundEvent shot(GunType type) {
        return switch (type) {
            case PISTOL -> GUN_PISTOL;
            case SMG -> GUN_SMG;
            case CARBINE -> GUN_RIFLE;
            case SHOTGUN -> GUN_SHOTGUN;
            case SNIPER -> GUN_SNIPER;
            case MINIGUN -> GUN_MINIGUN;
            case RPG -> RPG_LAUNCH;
        };
    }

    /** Our own blast on top of the vanilla one - heard across half the city. */
    public static void boom(ServerLevel level, double x, double y, double z) {
        level.playSound(null, x, y, z, EXPLOSION, SoundSource.BLOCKS, 8.0F, 0.9F + level.getRandom().nextFloat() * 0.2F);
    }

    public static void init() {
    }
}
