class_name InteriorManager
extends Node
## Enterable interiors (generated by Blender/scripts/generate_interiors.py):
##   safehouse (owned properties): bed = sleep, wardrobe, desk = save
##   store (convenience, supermarket, gas station, diner, electronics): counter + clerk
##   jewelry: smashable display cases + jeweler,  boutique (clothing): racks + clerk
##   gunshop: counter + shooting range minigame
## Every shop can be robbed: point a gun at the shopkeeper and keep it on them - they raise
## their hands and drop the takings bundle by bundle until the till is empty, then the alarm
## goes off and you have to get out. The gun shop owner fights back with a guard.
##   bank: lobby and vault (used by the heist)
## An interior is instanced 250 m below its building while the player is inside, lit by
## its own lights and an interior reflection probe (no sky light).

const DIR := "res://assets/generated/interiors/"
const DEPTH := 250.0
const TYPE_MAP := {
	"safehouse": "safehouse", "property_apartment": "safehouse", "property_house": "safehouse",
	"property_penthouse": "safehouse", "property_villa": "safehouse", "property_garage": "safehouse",
	"property_business": "safehouse",
	"shop_convenience": "store", "shop_supermarket": "store", "gas_station": "store", "diner": "store",
	"electronics": "store", "jewelry": "jewelry", "shop_clothing": "boutique",
	"shop_weapons": "gunshop", "bank": "bank",
}

var world: GameWorld
var meta := {}
var current: Node3D = null
var current_poi := {}
var current_kind := ""
var _markers: Array = []
var _npcs: Array = []
var _range := {}              # shooting range state
var _rob := {}                # active robbery state

const LOOT := {"shop_convenience": [1800, 3600], "gas_station": [1500, 3200], "shop_supermarket": [3500, 6500],
	"diner": [1200, 2600], "electronics": [7000, 13000], "shop_clothing": [2800, 5200], "jewelry": [9000, 15000],
	"shop_weapons": [16000, 26000]}
const ROB_WANTED := {"jewelry": 3, "shop_weapons": 3, "electronics": 2}
const ROB_DROPS := 6


func _ready() -> void:
	name = "Interiors"
	world = GameWorld.instance
	world.set_meta("interiors", self)
	var d = WorldData._read_json(DIR + "interiors.json")
	if d is Dictionary:
		meta = d
	# death / arrest respawns elsewhere: drop the interior without teleporting back
	Events.player_respawned.connect(func(_r): _discard())


func _discard() -> void:
	if current == null:
		return
	_stop_range(false)
	_rob = {}
	for m in _markers:
		if is_instance_valid(m):
			m.queue_free()
	_markers.clear()
	for n in _npcs:
		if is_instance_valid(n):
			n.queue_free()
	_npcs.clear()
	current.queue_free()
	current = null
	current_poi = {}
	current_kind = ""
	world.set_meta("in_interior", false)


static func get_manager() -> InteriorManager:
	var w := GameWorld.instance
	return w.get_meta("interiors") if w and w.has_meta("interiors") else null


func has_interior(poi_type: String) -> bool:
	return TYPE_MAP.has(poi_type) and meta.has(TYPE_MAP[poi_type])


func is_inside() -> bool:
	return current != null


# ------------------------------------------------------------------ enter / leave
func enter(poi: Dictionary, force := false) -> void:
	if current:
		return
	var kind: String = TYPE_MAP.get(poi["type"], "")
	if kind == "" or not meta.has(kind):
		return
	if not force and world.police and int(world.police.get("wanted_level")) > 0:
		Events.notify.emit("Die Tür ist verschlossen – du wirst gesucht.", 3.0)
		return
	var eco := world.economy as PoiManager
	await eco.fade_out_in(func(): _build(poi, kind))


func leave() -> void:
	if current == null:
		return
	var eco := world.economy as PoiManager
	await eco.fade_out_in(_teardown)


func _xform() -> Transform3D:
	var f: Vector3 = current_poi["facing_v"]
	var base: Vector3 = (current_poi["entrance_v"] as Vector3) - Vector3(0, DEPTH, 0)
	return Transform3D(Basis.looking_at(-f, Vector3.UP), base)


## World position of a named interior point.
func point(n: String) -> Vector3:
	var pts: Dictionary = meta[current_kind]["points"]
	if not pts.has(n) or current == null:
		return Vector3.INF
	var a: Array = pts[n]
	return current.global_transform * Vector3(a[0], a[1], a[2])


func point_yaw(n: String) -> float:
	var a: Array = meta[current_kind]["points"].get(n, [0, 0, 0, 0])
	return current.global_rotation.y + (float(a[3]) if a.size() > 3 else 0.0)


func _build(poi: Dictionary, kind: String) -> void:
	current_poi = poi
	current_kind = kind
	var scn: PackedScene = load(DIR + kind + ".glb")
	current = scn.instantiate()
	current.name = "Interior_" + kind
	world.add_child(current)
	current.global_transform = _xform()
	var m: Dictionary = meta[kind]
	var size: Array = m["size"]
	# lights
	for l in m["lights"]:
		var o := OmniLight3D.new()
		o.position = Vector3(l[0], l[1], l[2])
		o.omni_range = float(l[3])
		o.light_energy = float(l[4])
		var c: Array = l[5]
		o.light_color = Color(c[0], c[1], c[2])
		o.shadow_enabled = false
		current.add_child(o)
	var probe := ReflectionProbe.new()
	probe.interior = true
	probe.ambient_mode = ReflectionProbe.AMBIENT_COLOR
	probe.ambient_color = Color(0.55, 0.52, 0.48)
	probe.ambient_color_energy = 0.9
	probe.size = Vector3(float(size[0]) + 1.0, float(size[1]) + 1.0, float(size[2]) + 1.0)
	probe.position = Vector3(0, float(size[1]) * 0.5, -float(size[2]) * 0.5)
	probe.update_mode = ReflectionProbe.UPDATE_ONCE
	current.add_child(probe)
	# player
	var p := world.player as Player
	var sp: Vector3 = point("spawn")
	p.teleport(sp + Vector3.UP * 0.1)
	p.rotation.y = current.global_rotation.y
	if p.cam:
		p.cam.yaw = p.rotation.y
	world.set_meta("in_interior", true)
	_add_marker(point("exit") + current.global_basis.z * -0.2, "E: Verlassen", Color(0.9, 0.9, 0.9), func(_pl): leave())
	var eco := world.economy as PoiManager
	match kind:
		"safehouse":
			_add_marker(point("bed"), "E: Schlafen", Color(0.35, 0.95, 0.5), func(_pl): eco._sleep())
			_add_marker(point("wardrobe"), "E: Garderobe", Color(0.75, 0.5, 0.95), func(_pl): eco._open_wardrobe())
			_add_marker(point("save"), "E: Spiel speichern", Color(0.35, 0.95, 0.5), func(_pl): eco._open_save_menu())
		"store":
			_shopkeeper()
			_add_marker(point("counter"), "E: Einkaufen", Color(0.3, 0.8, 0.35), func(pl): eco._open_store(pl, poi))
		"jewelry":
			_shopkeeper()
			_spawn_cases()
			_add_marker(point("counter"), "E: Juwelier", Color(0.75, 0.85, 1.0), func(pl): eco._open_store(pl, poi))
		"boutique":
			_shopkeeper()
			_add_marker(point("counter"), "E: Kleidung kaufen", Color(0.75, 0.5, 0.95), func(pl): eco._open_clothing(pl, poi))
		"gunshop":
			var owner := _shopkeeper()
			if owner:
				owner.shop_role = "gunshop"
				owner.bravery = 1.0
				owner.health.max_health = 320.0
				owner.health.health = 320.0
				owner.weapons.give("shotgun", 80)
				owner.weapons.accuracy = 0.8
			_add_marker(point("counter"), "E: Waffen kaufen", Color(0.95, 0.3, 0.3), func(pl): eco._open_weapons(pl, poi))
			_add_marker(point("range"), "E: Schießstand ($50)", Color(0.3, 0.8, 1.0), func(_pl): _start_range())
		"bank":
			_clerk("teller", "business")
	Events.notify.emit(String(poi["name"]), 2.0)


func _teardown() -> void:
	_stop_range(false)
	_rob = {}
	for m in _markers:
		if is_instance_valid(m):
			m.queue_free()
	_markers.clear()
	for n in _npcs:
		if is_instance_valid(n):
			n.queue_free()
	_npcs.clear()
	var p := world.player as Player
	var poi := current_poi
	var out: Vector3 = (poi["entrance_v"] as Vector3) + (poi["facing_v"] as Vector3) * 2.5
	world.streaming.load_area_blocking(out, 200.0)
	p.teleport(out + Vector3.UP * 0.2)
	var f: Vector3 = poi["facing_v"]
	p.rotation.y = atan2(-f.x, -f.z)
	if p.cam:
		p.cam.yaw = p.rotation.y
	current.queue_free()
	current = null
	current_poi = {}
	current_kind = ""
	world.set_meta("in_interior", false)


func _add_marker(pos: Vector3, prompt: String, col: Color, cb: Callable) -> void:
	if pos == Vector3.INF:
		return
	var m := InteractMarker.new()
	m.prompt = prompt
	m.color = col
	m.interact_radius = 1.6
	m.on_interact = cb
	world.add_child(m)
	m.global_position = pos
	_markers.append(m)


func _clerk(pt := "clerk", role := "civilian") -> NPC:
	var pos := point(pt)
	if pos == Vector3.INF or world.peds == null:
		return null
	var n: NPC = world.peds.call("spawn_npc", pos + Vector3.UP * 0.05, role, {}, true)
	n.rotation.y = point_yaw(pt)
	n._set_state(NPC.S.WORK)
	n._timer = 1e9
	_npcs.append(n)
	return n


func _shopkeeper() -> NPC:
	var n := _clerk("clerk", "business")
	if n:
		n.shop_role = "clerk"
	return n


# ------------------------------------------------------------------ robberies
## Called by the shopkeeper while the player points a gun at them (or shoots in the shop).
func clerk_threatened(n: NPC, p: Node3D) -> void:
	if current == null:
		return
	if n.shop_role == "gunshop":
		_gunshop_fight(n, p)
		return
	if _rob.is_empty():
		_start_robbery(n)
	_rob["aim_t"] = 0.0
	if n.state != NPC.S.HANDS_UP:
		n._face(p.global_position)
		n.hands_up(3.0)


func _robbed_today() -> bool:
	var robbed: Dictionary = Game.player_data.world_state.get("robbed", {})
	var id := str(int(current_poi.get("id", -1)))
	var day: int = world.day_night.day if world.day_night else 0
	return robbed.has(id) and day - int(robbed[id]) < 1


func _mark_robbed() -> void:
	var robbed: Dictionary = Game.player_data.world_state.get("robbed", {})
	robbed[str(int(current_poi.get("id", -1)))] = world.day_night.day if world.day_night else 0
	Game.player_data.world_state["robbed"] = robbed


func _start_robbery(n: NPC) -> void:
	var t: String = current_poi["type"]
	var empty := _robbed_today()
	var r: Array = LOOT.get(t, [1500, 3000])
	_rob = {"clerk": n, "total": 0 if empty else randi_range(r[0], r[1]), "paid": 0, "drops": 0, "timer": 0.9,
		"aim_t": 0.0, "alarm": 4.0, "alarmed": false, "done": empty, "register": false}
	_mark_robbed()
	n.say("robbed_out" if empty else ("jeweler" if t == "jewelry" else "surrender"))
	if empty:
		Events.big_message.emit("ÜBERFALL", "Die Kasse ist leer – hier wurde heute schon abkassiert.", 3.0)
	else:
		Events.big_message.emit("ÜBERFALL", "Halte die Waffe auf den Verkäufer!", 2.5)
	Events.crime_committed.emit("robbery", current_poi["entrance_v"], 3, world.player)


func _update_robbery(delta: float) -> void:
	var n: NPC = _rob["clerk"] if is_instance_valid(_rob["clerk"]) else null
	if not bool(_rob["alarmed"]):
		_rob["alarm"] = float(_rob["alarm"]) - delta
		if float(_rob["alarm"]) <= 0.0 or n == null or n.is_dead():
			_alarm()
	if bool(_rob["done"]):
		return
	if n == null or n.is_dead():
		# nobody behind the counter any more: the till can be emptied by hand
		if not bool(_rob["register"]):
			_rob["register"] = true
			_add_marker(point("counter"), "E: Kasse leeren", Color(0.3, 1.0, 0.4), func(_pl): _empty_register())
		return
	if bool(_rob.get("gun", false)):
		return
	_rob["aim_t"] = float(_rob["aim_t"]) + delta
	if float(_rob["aim_t"]) > 1.6:
		Events.subtitle.emit("Halte die Waffe auf den Verkäufer – sonst rückt er nichts raus!", 0.3)
		return
	Events.subtitle.emit("Ausrauben: %d / %d   ·   $%d" % [int(_rob["drops"]), ROB_DROPS, int(_rob["paid"])], 0.3)
	_rob["timer"] = float(_rob["timer"]) - delta
	if float(_rob["timer"]) > 0.0:
		return
	_rob["timer"] = 1.3
	var total := int(_rob["total"])
	var drops := int(_rob["drops"]) + 1
	var amt := total / ROB_DROPS if drops < ROB_DROPS else total - int(_rob["paid"])
	var p := world.player as Player
	var to_player := p.global_position - n.global_position
	to_player.y = 0.0
	var pos := n.global_position + to_player.normalized() * minf(1.6, to_player.length() * 0.6)
	pos += Vector3(randf_range(-0.4, 0.4), 0.0, randf_range(-0.4, 0.4))
	var jewels: bool = current_poi["type"] == "jewelry"
	Pickup.spawn(current, pos, "jewels" if jewels else "money", amt)
	AudioManager.play_3d("reload", n.global_position + Vector3.UP, -10.0, 1.6)
	_rob["drops"] = drops
	_rob["paid"] = int(_rob["paid"]) + amt
	if drops == 3:
		n.say("surrender")
	if drops >= ROB_DROPS:
		_rob["done"] = true
		n.say("robbed_out")
		_alarm()
		Game.player_data.stat_add("robberies", 1)
		Events.big_message.emit("LADEN AUSGERAUBT", "Schnapp dir die Beute und verschwinde!", 3.0)


func _alarm() -> void:
	if _rob.is_empty() or bool(_rob["alarmed"]):
		return
	_rob["alarmed"] = true
	var lvl: int = ROB_WANTED.get(current_poi["type"], 2)
	if world.police:
		world.police.call("set_wanted", maxi(int(world.police.get("wanted_level")), lvl))
	Events.notify.emit("Alarm ausgelöst! Die Polizei ist unterwegs.", 3.0)


func _empty_register() -> void:
	if _rob.is_empty() or bool(_rob["done"]):
		return
	var rest := int(_rob["total"]) - int(_rob["paid"])
	_rob["done"] = true
	_alarm()
	if rest > 0:
		Game.player_data.add_money(rest, "robbery")
		AudioManager.play_ui("money")
	Game.player_data.stat_add("robberies", 1)
	Events.big_message.emit("KASSE GELEERT", "+$%d – jetzt nichts wie weg!" % rest, 3.0)


## The gun shop owner does not hand anything over: he and his guard open fire.
func _gunshop_fight(n: NPC, p: Node3D) -> void:
	if n.hostile or not _rob.is_empty():
		return
	n.hostile = true
	n.say("gunshop")
	n.engage(p)
	var gp := point("range")
	if gp != Vector3.INF and world.peds:
		var g: NPC = world.peds.call("spawn_npc", gp + Vector3.UP * 0.05, "business", {}, true)
		g.bravery = 1.0
		g.hostile = true
		g.health.max_health = 180.0
		g.health.health = 180.0
		g.weapons.give("rifle", 150)
		g.weapons.accuracy = 0.7
		g.engage(p)
		_npcs.append(g)
	var r: Array = LOOT["shop_weapons"]
	_rob = {"clerk": n, "total": randi_range(r[0], r[1]), "paid": 0, "drops": 0, "timer": 0.0, "aim_t": 0.0,
		"alarm": 0.5, "alarmed": false, "done": _robbed_today(), "register": false, "gun": true}
	_mark_robbed()
	Events.big_message.emit("SCHIESSEREI", "Der Waffenhändler wehrt sich!", 2.5)
	Events.crime_committed.emit("robbery", current_poi["entrance_v"], 3, world.player)


# ------------------------------------------------------------------ jewelry display cases
func _spawn_cases() -> void:
	var pts: Dictionary = meta[current_kind]["points"]
	var empty := _robbed_today()
	for k in pts:
		if not String(k).begins_with("case_"):
			continue
		var c := DisplayCase.new()
		c.value = 0 if empty else randi_range(1800, 3800)
		current.add_child(c)
		c.global_position = point(k)
		c.global_rotation.y = current.global_rotation.y
		c.smashed.connect(_on_case_smashed)


func _on_case_smashed(_c: Node) -> void:
	if _rob.is_empty() or not bool(_rob["alarmed"]):
		if _rob.is_empty():
			_rob = {"clerk": null, "total": 0, "paid": 0, "drops": ROB_DROPS, "timer": 0.0, "aim_t": 0.0,
				"alarm": 0.0, "alarmed": false, "done": true, "register": true}
			_mark_robbed()
			Events.crime_committed.emit("robbery", current_poi["entrance_v"], 3, world.player)
		_alarm()
		for n in _npcs:
			if is_instance_valid(n) and (n as NPC).shop_role == "clerk":
				(n as NPC).hands_up(6.0)
				(n as NPC).say("jeweler")


# ------------------------------------------------------------------ shooting range minigame
func _start_range() -> void:
	var p := world.player as Player
	if not _range.is_empty():
		return
	if not p.weapons.has_ranged():
		Events.notify.emit("Du brauchst eine Schusswaffe. Kauf eine an der Theke.", 3.0)
		return
	if not Game.player_data.add_money(-50, "range"):
		Events.notify.emit("Nicht genug Geld.", 2.0)
		return
	for id in p.weapons.owned_sorted():
		if WeaponData.is_ranged(id):
			p.weapons.equip(id)
			p.weapons.add_ammo(id, 60)
			break
	var targets := []
	for i in 3:
		var tp := point("target_%d" % i)
		if tp == Vector3.INF:
			continue
		var t := RangeTarget.new()
		t.manager = self
		current.add_child(t)
		t.global_position = tp
		t.global_rotation.y = current.global_rotation.y
		targets.append(t)
	_range = {"targets": targets, "score": 0, "time": 30.0, "active_i": -1, "timer": 0.0}
	Events.big_message.emit("SCHIESSSTAND", "Triff die aufleuchtenden Ziele – 30 Sekunden", 2.5)


func range_hit(t: Node) -> void:
	if _range.is_empty():
		return
	if (t as RangeTarget).lit:
		_range["score"] = int(_range["score"]) + 1
		AudioManager.play_ui("checkpoint", -8.0)
		(t as RangeTarget).set_lit(false)
		_range["timer"] = 0.0


func _process(delta: float) -> void:
	if not _rob.is_empty() and current:
		_update_robbery(delta)
	if _range.is_empty():
		return
	_range["time"] = float(_range["time"]) - delta
	_range["timer"] = float(_range["timer"]) - delta
	if float(_range["timer"]) <= 0.0:
		_range["timer"] = randf_range(1.0, 1.8)
		var ts: Array = _range["targets"]
		for t in ts:
			(t as RangeTarget).set_lit(false)
		if not ts.is_empty():
			(ts[randi() % ts.size()] as RangeTarget).set_lit(true)
	Events.subtitle.emit("Treffer: %d   ·   Zeit: %d s" % [int(_range["score"]), maxi(0, int(_range["time"]))], 0.3)
	if float(_range["time"]) <= 0.0:
		_stop_range(true)


func _stop_range(pay: bool) -> void:
	if _range.is_empty():
		return
	var score := int(_range["score"])
	for t in _range["targets"]:
		if is_instance_valid(t):
			t.queue_free()
	_range = {}
	if pay:
		var reward := score * 20
		if reward > 0:
			Game.player_data.add_money(reward, "range")
		Events.big_message.emit("ERGEBNIS: %d TREFFER" % score, "+$%d" % reward, 3.5)
		var best := int(Game.player_data.stats.get("range_best", 0))
		if score > best:
			Game.player_data.stats["range_best"] = score
			Events.notify.emit("Neuer Rekord am Schießstand!", 3.0)
